name: Auto Commit Daily at 5 PM IST

on:
  schedule:
    - cron: '30 11 * * *'  # Runs every day at 11:30 AM UTC (5:00 PM IST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto Commit Changes
        run: |
          # Create or modify a file
          echo "Auto commit at 5 PM IST on $(date)" > daily_update.txt

          # Configure Git user information
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"

          # Stage, commit, and push changes
          git add .
          git commit -m "Auto commit: 5 PM IST on $(date)"
          git push origin main  # Change 'main' if your default branch is different
